### ISSUE TITLE
!session command not working anymore

### ISSUE THREAD

**Issue by mmabrouk** [mmabrouk/chatgpt-wrapper#101]
It appears that the session command is no longer functioning properly. The code appears to be stuck in an infinite loop at the refresh_session step.
Perhaps @Tecuya  you could take a look into this issue, given that you're the expert :) ?

**Comment by AndPim4912** [comment]
I think, refresh_session method stucks into infinite loop because it executes https://chat.openai.com/api/auth/session request on cloudflare page and this request returns 401 - Unauthorized. Then in while loop it tries to retrieve appended child without repeting the request. Manually checking cloudflare "I'm not a robot" checkbox (css_selector: .mark) or "I'm not robot" button (css unknown) and repeating the evaluation of xhr code from F12 console breaks infinite loop. So, to fix this bug we need to add check, if evaluated xhr rises 401, if page has cloudflare  protection elements. If it is, click checkboxes and buttons, repeat xhr and select appended child div.
I'm not familar with playwright and git, so preparing pull request may take a while.

**Comment by AndPim4912** [comment]
> I think, refresh_session method stucks into infinite loop because it executes https://chat.openai.com/api/auth/session request on cloudflare page and this request returns 401 - Unauthorized. Then in while loop it tries to retrieve appended child without repeting the request. Manually checking cloudflare "I'm not a robot" checkbox (css_selector: .mark) or "I'm not robot" button (css unknown) and repeating the evaluation of xhr code from F12 console breaks infinite loop. So, to fix this bug we need to add check, if evaluated xhr rises 401, if page has cloudflare protection elements. If it is, click checkboxes and buttons, repeat xhr and select appended child div. I'm not familar with playwright and git, so preparing pull request may take a while.

The second type of challenge is button
#challenge-stage > div:nth-child(1) > input:nth-child(1)
value="Verify you are human"

**Comment by mmabrouk** [comment]
The problem should have been fixed in #153
