### ISSUE TITLE
Playbooks/workflows

### ISSUE THREAD

**Issue by thehunmonkgroup** [mmabrouk/chatgpt-wrapper#165]
Not sure if this is a good idea or not, but it's occurred to me another possible timesaver, along with #148 , would be some kind of simple playbook/workflow functionality.

Consider this workflow:

```
Me: Write a 200 word essay about bacon.
...ChatGPT responds...
Me: Provide critical feedback on the essay, with a focus on
improving clarity, etc.
...ChatGPT responds...
Me: Rewrite the original essay making adjustments based on
the critical feedback you provided
```

If you had a typical workflow like that, wouldn't it be nice to have the wrapper automatically submit the next prompt once ChatGPT responds?

One simple way to implement this would be to use Markdown thematic breaks: https://spec.commonmark.org/0.30/#thematic-break

In that case, the above prompt would look like this:

```
Write a 200 word essay about bacon.
---
Provide critical feedback on the essay, with a focus on
improving clarity, etc.
---
Rewrite the original essay making adjustments based on the
critical feedback you provided
```

I'm not 100% sure this is a good idea, but throwing it out there for consideration.

**Comment by rebroad** [comment]
Yes, I also need it to be able to continue from previous conversations. Ideally there could be a way to label the conversations and give that as a command line argument so that it knows which conversation to resume.

**Comment by thehunmonkgroup** [comment]
Not sure I understand what you're asking for. Perhaps you could describe it more, or better, show some example commands and output?

**Comment by rebroad** [comment]
> Not sure I understand what you're asking for. Perhaps you could describe it more, or better, show some example commands and output?

I mean that in Chat-GPT there are multiple conversations (each with their own title, generated based on the first thing said, a summary), and it would be useful to be able to resume existing conversations rather than starting a new one each time (which the chatgpt command line in non-interactive mode currently does).

**Comment by thehunmonkgroup** [comment]
I guess I'm still not clear how you envision this working. Right now from the wrapper shell, you can do `/switch` to resume an existing conversation.

You're asking for a command line switch to allow a one-shot run of the wrapper to send the prompt to a specific conversation?

If so, I don't see how that pertains to this issue.

**Comment by mmabrouk** [comment]
@thehunmonkgroup, I think your proposal is excellent, and I wanted to share some additional insights that might be helpful. I came across a paper (https://arxiv.org/abs/2302.07842) that discusses how LLM models can be augmented using different techniques. The paper proposes three techniques, one of which is based on prompting, and I believe it is particularly relevant to your proposal.

The paper describes two types of prompting techniques that could be useful in designing workflows. The first is chain-of-thought prompts, where the prompt consists of examples of a task, with inputs followed by intermediate reasoning steps leading to the final output. Let's say you want the LLM to explain the root cause of a bug in the code in a specific way, rather than giving a low-level description. In that case, instead of asking the LLM directly, you could provide an example of a question and answer, and then ask the bot to answer in the same way. This kind of prompts can be implemented using the jinja2 templates we discussed.

Another kind of chain-of-thought prompts are exactly like the ones in this proposal. You ask a first question then follow up with a number of questions. 

The third type of prompting is recursive prompting, where the LLM is first asked to decompose the problem into sub-prompts and then run the sub-prompts. This is similar to the workflow you proposed, but it has the added requirement that the output of the original prompt is used as an input to subsequent prompts.

In addition to these prompting techniques, the paper also discusses using other information sources (e.g., Google, code base, embedding database) and calling APIs to act in the world. These techniques are also very interesting and could be useful in augmenting LLM models.

I am very excited about these techniques as they have the potential to greatly enhance productivity. Think of each of these "workflows" as a recipe for creating specialized agents. For example, one agent could be designed to debug your Python code more efficiently by utilizing API documentation for each call made in your code. Here's how it would work:

1. Prompt the model to provide all the calls made in your code.
2. Search for the relevant public API documentation and save the useful ones.
3. Look for all the internal method definitions in your codebase.
4. Finally, prompt the model with the original code, error, and the collected API documentation.

Other agents could be created to summarize interesting articles found on the internet and organize them into your personal knowledge database, create a personal CRM, or distill relevant conversations from Slack groups you follow.

I believe this goes far beyond the scope of the current issue :D

**Comment by thehunmonkgroup** [comment]
After having done some initial research on https://github.com/hwchase17/langchain, I pretty sure we'll want to leverage this or a similar toolchain for this feature.

**Comment by thehunmonkgroup** [comment]
Workflows are implemented for the API backend. They will not be implemented for the browser backend.
