### ISSUE TITLE
How can I do multiline input?

### ISSUE THREAD

**Issue by thisismygitrepo** [mmabrouk/chatgpt-wrapper#24]
As soon as I press enter or shift+enter for a newline, it submits the query immediately. How can I put in a multiline input?
This is probably a terminal limitation.

**Comment by Tecuya** [comment]
Yeah we are using `cmd` which uses `input` which only accepts single lines.

I made a variant once where you had to hit enter twice to submit a question.  That allowed for basic multiline input.  But it was kind of obtrusive and I got rid of it.  

There are a few different approaches we could take.

* Make it so lines with a trailing backslash allow you to continue the same message on the next line.  In order to make this work cleanly I'd have to override some behavior of the `cmd` module..
* Some kind of "begin" and "end" commands that start and end multi-line messages.  I'd have to add code to prevent the other commands such as nav and new from being used during multi-line input or the state would get too weird.
* Make it so if the user adds some special string of characters, such as "\\n" or something, that that string is replaced with an actual newline before we transmit it to ChatGPT.

None of them are perfect.. I think "begin" and "end" are probably the cleanest?
