### ISSUE TITLE
Best way to manage 2 accounts?

### ISSUE THREAD

**Issue by robbintt** [mmabrouk/chatgpt-wrapper#255]
I would like to put each of my 2 openai accounts in a separate chatgpt-wrapper profile and give playwright separate configurations per profile. Is there a straightforwards way I can implement this?

**Comment by thehunmonkgroup** [comment]
Not currently.

I'm not sure I want to introduce this kind of complexity, either, the Playwright stuff can already be a bit flaky.

Plus, the API backend already has multiple account management built in.

**Comment by robbintt** [comment]
I was thinking Playwright might have its own concept of session I could use.

**Comment by thehunmonkgroup** [comment]
It's important to keep in mind that the browser backend is ultimately an unofficial hack, and while it still has its uses (like GPT-4 access for Plus users that don't have the access via the API yet), it's most likely to suffer a slow death, and not get much in the way of new features.

The recent announcement of plugins may delay that decline, hard to say at this point.

**Comment by thehunmonkgroup** [comment]
@robbintt it occurred to me that since profiles already have their own data directory, it would be trivial to store the playwright session there, instead of its current global location.

https://github.com/mmabrouk/chatgpt-wrapper/releases/tag/v0.7.1 has implemented this change, give it a try and see if it works for your needs -- in my light testing it appears to work fine.

**IMPORTANT NOTES:**
1. If this change results in a slew of bug reports, I may roll it back.
2. Keep in mind that this results in an entirely new browser instance being run per profile, so I wouldn't go nuts running a bunch of profiles at the same time.

**Comment by robbintt** [comment]
Awesome, that's similar to what I was thinking. I am going to try it out today.

**Comment by robbintt** [comment]
I am having an issue. Everything looks good. I installed on 2 accounts by specifying `-p <profile>` for each, and when I repeat the install, they each bring up a logged in browser on their individual playwright accounts. However, when I start a session, I get the message:

`chatgpt -p robbintt --config-dir $WORKDIR --data-dir $WORKDIR/data/`
```
                        Provide a prompt for ChatGPT, or type /help or ? to list commands.                         

1> test

Your ChatGPT session is not usable.
* Run this program with the `install` parameter and log in to ChatGPT.
* If you think you are already logged in, try running the `session` command.

2> /session

 • Session information refreshed.  The session is not usable.  Try install mode. 
```

I haven't tried to debug it yet

**Comment by robbintt** [comment]
The global profile seems to be working fine, including the browser session. It must be some specific bug restoring the per-profile browser sessions after a per profile install.

**Comment by robbintt** [comment]
This feature works fine, I had a custom data directory. Once I removed that, it worked. 

When I had the issue, I didn't install to the custom data directory, I had two data directories.
