### ISSUE TITLE
Can we have the ability to save a log of our prompts and ChatGPT responses to a text file?

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#26]
I think this would be useful if I were using this for something I wanted to save for later. I'm blind, so screenshots just don't cut it.

**Comment by Tecuya** [comment]
If you are on Linux or macOS you can use the `script` command when running chatgpt-wrapper to store the output to a file.  Example:

```
sean@creosote:~$ script -c chatgpt mylog.txt
Script started, output log file is 'mylog.txt'.
Provide a prompt for ChatGPT, or type help or ? to list commands.
1> hello there

Hello! It's nice to meet you. Is there anything you'd like to talk about today? I'm here to help with any questions you may have.                             

2> exit
Script done.
sean@creosote:~$ cat mylog.txt 
Script started on 2022-12-11 16:18:12-08:00 [COMMAND="chatgpt" TERM="xterm" TTY="/dev/pts/0" COLUMNS="158" LINES="39"]
Provide a prompt for ChatGPT, or type help or ? to list commands.
1> hello there

Hello! It's nice to meet you. Is there anything you'd like to talk about today? I'm here to help with any questions you may have.                             

2> exit

Script done on 2022-12-11 16:18:21-08:00 [COMMAND_EXIT_CODE="0"]
```

**Comment by jaybird110127** [comment]
Thanks. However, I'm on Windows, so that command won't work for me. I tried using the start-transcript command under PowerShell but for some reason Chatgpt couldn't find my existing session. I almost never use PowerShell, but rather, CMD or a CMD replacement.

**Comment by jaybird110127** [comment]
Okay, I've found a workaround. Launch my CMD replacement, then from there, launch PowerShell. Then I can use the start-transcript command and then run Chatgpt. I still think it would be good to have logging/transcripting support from within the program itself E.G. a "log" command or some such. Maybe I only want certain parts of my session logged, etc.

**Comment by jaybird110127** [comment]
I've found a problem with the PowerShell transcript method. Apparently PowerShell's transcripts actually capture where line breaks occur on the screen, rather than the raw text the program outputs, so in ChatGPT responses I get unwanted hard line breaks. This is just one reason I feel the program should have built-in logging support.

**Comment by Tecuya** [comment]
Interesting.  It's too bad powershell transcripts don't fit the bill..  

Yeah the thing is to add this, it would add a bit of complication, as I'd need to change all the statements that print output so that they know capture output, conditionally write it to a log, then print it..   in the case of output from the `cmd` module which chatgpt-wrapper relies on, this wouldn't be possible without overriding some basic pieces of the `cmd` modules functionality and that would be difficult to maintain..

There's gotta be a better way to capture the output from the program in Windows.  I think if you install cygwin or WSL you can have the actual `script` command available in bash shells (not in CMD.exe that I'm aware of)

I googled around to try and find something that would work for you.  I did see [this](https://github.com/mattn/ttyrec4windows) though it captures to ttyrec files and not to raw ascii files, so this may not work..

**Comment by jaybird110127** [comment]
Okay, so why not, instead of capturing text at the i/o stage, capture it later for input, and earlier for output? E.G. once a prompt is received, just before it's sent to ChatGPT, write it to the log, as it was received. Then, when the response comes in, do whatever formatting needs to be done to it, then log it, then output it to the console.

**Comment by Tecuya** [comment]
Yeah as long as we are talking about only writing prompts and responses to the log file, it's quite doable.  

I might try adding that soon

**Comment by Tecuya** [comment]
OK I've added a `log` command to enable logging to a file.

It writes prompts, responses, and context changes.  

The context changes include identifiers that can be loaded back in to the program using the `context` command.  This way you can revisit any historic context that you ever logged.
