### ISSUE TITLE
requirements.txt  should add  version in it

### ISSUE THREAD

**Issue by foce123** [mmabrouk/chatgpt-wrapper#268]
PyYAML>=5.4.1
sqlalchemy<2

then, docker build will go on

**Comment by thehunmonkgroup** [comment]
The code actually works on SQLAlchemy 2.x, however, the langchain dependency forces it back down to 1.x

I don't believe we need version requirements for either of those packages, because:

1. pip should install the latest version of PyYAML
2. pip will automatically resolve SQLAlchemy to the 1.x version if you install the deps via the recommended method

So can you please explain to me why these changes are needed in the Docker case?

**Comment by foce123** [comment]
my env:
OS: Centos 7.9

conda create -n test python=3.8
conda activate test
pip install -r requirements.txt
pip install docker-compose
docker-compose up -d

then, the error info is:   
#0 5.324 error: SQLAlchemy 2.0.8 is installed but SQLAlchemy<2,>=1 is required by {'langchain'}

**Comment by thehunmonkgroup** [comment]
This seems wrong:

* Why is SQLAlchemy installed in the first place? This is a Docker container, it should be devoid of packages like that until you run the setup.
* Even if it was installed, pip should  properly handle the dependency resolution and download/activate a version of the package that is compatible with all other packages.
* Still no explanation on the PyYAML thing, either.

**Comment by foce123** [comment]
In my latest docker build, there wasn't problem occurred on the PyYAML.

**Comment by thehunmonkgroup** [comment]
That's progress, and what about SQLAlchemy, why is it already installed in the container when you try to install the deps?
