### ISSUE TITLE
Proposal to simplify API key setup using Python API

### ISSUE THREAD

**Issue by 1core2life** [mmabrouk/chatgpt-wrapper#284]
- When a terminal is closed, the current env variable settings are not preserved. 
- Because Env variables are only maintained for the current terminal session in use.
- OPENAI_API_KEY is set through env variables. So it can be disappear easily.

When we use code with Python API, Why don't we let them write it directly on the code? same as [python-twitter](https://github.com/bear/python-twitter)
It will reduce the process of setting variables repeated for each new session.

pros
- Simplifies the API key setup process for users.
- Eliminates the need to reset the API key for each new terminal session.
- Improves the user experience and reduces the likelihood of errors due to incorrect API key setup.

For example.
```
from chatgpt_wrapper import OpenAIAPI

api_key = {YOUR_OPENAI_API_KEY}

bot = OpenAIAPI(key=api_key)
bot.set 
success, response, message = bot.ask("Hello, world!")
if success:
    print(response)
else:
    raise RuntimeError(message)
```

**Comment by thehunmonkgroup** [comment]
Because the long  term plan for this project is to support LLMs from multiple providers, I'm currently thinking that providing direct mechanisms to set API keys on the class will make the code harder to maintain.

There are already multiple standard mechanisms for managing environment variables in various shell/deployment scenarios, they should be pretty easy to implement.

And if you really want to put it in code, use the standard Python mechanism for doing that.
