### ISSUE TITLE
chatgpt install not working

### ISSUE THREAD

**Issue by samsap** [mmabrouk/chatgpt-wrapper#46]
When I run "chatgpt install" on Terminal (Mac) I get the following error:

zsh: command not found: chatgpt

BTW, I get the same error when I run "playwright install" and got around it by running "python3 -m playwright install"

Any help is appreciated!

**Comment by mindgitrwx** [comment]
You can get chatgpt installed path by this
`
which chatgpt
`
In my case, /Users/jhyeo/Library/Python/3.9/bin/chatgpt

And this line on your .zshrc file
`
export PATH="$PATH:/Users/jhyeo/Library/Python/3.9/bin"
`

And run `source .zshrc`

**Comment by jbmestelan** [comment]
I would consider the `which` command unlikely to work, as it provides an entry only for files in the $PATH (the problem here being that `chatgpt` is not).

The `chatgpt` executable should be installed as specified by pip/setuptools:
from setup.py:
```
entry_points={
        "console_scripts": [
            "chatgpt = chatgpt_wrapper.chatgpt:main"
        ]
    },
```

 You can learn more about it by running 
` pip show -v chatgpt`

In my case, the `chatgpt` exe is located in `~/.local/bin`; and the pip install command had issued this warning:

> WARNING: The script chatgpt is installed in '/home/me/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
