### ISSUE TITLE
Your ChatGPT session is not usable.

### ISSUE THREAD

**Issue by 17Reset** [mmabrouk/chatgpt-wrapper#81]
I tried to use chapt-wrapper in python like this, but I encountered this problem.
from chatgpt_wrapper import ChatGPT
bot = ChatGPT()
# return the full result
response = bot.ask("what day is today")
print(response)

problem:
Your ChatGPT session is not usable.
* Run this program with the `install` parameter and log in to ChatGPT.
* If you think you are already logged in, try running the `session` command.

**Comment by crexlight** [comment]
i have this problem too

**Comment by brmi1** [comment]
+1

**Comment by crexlight** [comment]
I fixed it like this
```
import os
os.system('chatgpt install')
```

After that it worked

**Comment by mmabrouk** [comment]
The problem should have been fixed in #153

**Comment by HaniItani** [comment]
Hello @mmabrouk,

I'm still running into the same error with the most recent version of the repo. I also had to add `import nest_asyncio;
nest_asyncio.apply()` to the top of `chatgpt.py` otherwise I get a "This event loop is already running" error.

Any guidance would be greatly appreciated.
Best regards,
Hani
